### ISSUE TITLE
自動デプロイしたい

### ISSUE THREAD

**Issue by oshanQQ** [o-xian999/nyanchu-megaphone#10]
## WHY

GitHub Actionsで自動でアプリをデプロイできるようにしたい。全部GitHubで完結するからコンパクトになりそう。
## WHAT

GitHub Actionsで、アプリをGitHub Pagesに自動デプロイできるようにする。

**Comment by kugimasa** [comment]
コメント失礼します🙇‍♂️

GitHub Pagesだと静的サイトのみしかHostingできないので、
動的サイトの場合はFirebaseやHerokuといった他のホスティングサービスの方が良いと思います。

**Comment by oshanQQ** [comment]
@kugimasa 
めちゃくちゃ重要ですね、ありがとうございます。
Next.jsだと開発元のVercelが提供しているホスティングサービスもあるらしいので要調査ですね 🤔

**Comment by oshanQQ** [comment]
Vervelにデプロイします。

**Comment by oshanQQ** [comment]
#21 でけた
