### ISSUE TITLE
Reactのコードを見てもらいたい

### ISSUE THREAD

**Issue by oshanQQ** [o-xian999/nyanchu-megaphone#11]
## WHY

React初心者が書いたコードは至らないところが多いはず。
## WHAT

誰かにコードをレビューしてもらう

**Comment by ssssota** [comment]
https://github.com/o-xian999/nyanchu-megaphone/blob/960a8a9a5f59d6e903d071ddb3b41bd3f9302cac/pages/index.tsx#L5

`body`じゃなく`main`とかが相応しい

bodyはNextの機能で自動的に挿入される
